In [42]:
from numpy import *

In [3]:
b = array([1, 2, 3, 4])   #1
b = zeros(10)  
b[4] = 1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [14]:
a = arange(10, 50)   #2
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
a = array([1, 2, 3, 4, 5, 6, 7, 8])   #3
b = a[::-1]
a, b

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([8, 7, 6, 5, 4, 3, 2, 1]))

In [8]:
a = arange(9).reshape(3, 3)   #4
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
a = [1,2,0,0,4,0]    #5
b = nonzero(a)
b

(array([0, 1, 4], dtype=int64),)

In [9]:
a = random.randint(-30, 30, (3, 3, 3))   #6
a

array([[[-11,  14,  21],
        [-20, -15,  14],
        [ 27,  -2,  14]],

       [[-15,  -4, -17],
        [-10,   2, -23],
        [-14,   7, -12]],

       [[ -9,  22, -28],
        [-29, -14,  14],
        [ -5, -28,  24]]])

In [17]:
a = random.randint(-50, 50, (10, 10))    #7
maxi = amax(a)
mini = amin(a)
a

array([[ 13,  19,  23,  45,  41, -13, -49,  15,   3, -26],
       [-28,  -4,   4, -23, -26,   3, -31,  14,  13,  46],
       [ 17,  14, -44, -43, -19, -13, -49, -25,  37, -45],
       [ -6,   2, -50, -33,  19,  -4,  13, -50,  -4,  -3],
       [ 11, -18, -23, -20, -13,  32, -36, -15,   1,  24],
       [ 44,  -5, -19, -14,  41,  23,  45, -23,   5, -38],
       [ -3,   6,  -5,  -2,  -1,  21,  28,  34, -22, -14],
       [-23, -18,  37, -13, -20,   9,  43, -17,  20, -25],
       [ -2,  40,   6, -26, -36,  30, -48,   3, -21,  -5],
       [  1, -12, -17, -36, -45, -14,   6, -45,  25,   3]])

In [18]:
maxi = amax(a)
mini = amin(a)
maxi, mini

(46, -50)

In [14]:
a = random.randint(1, 100, (30))    #8
a

array([79, 77, 68, 14, 57, 96, 14, 78, 37, 71, 23, 76, 38, 24, 65, 86, 52,
       17, 78, 44, 64, 92, 59,  9, 59, 46, 14, 84, 10, 76])

In [15]:
mean = mean(a)
mean

53.56666666666667

In [26]:
a = ones((5,5))         #9
print(a)
print("0 on the border")
a [1: -1, 1: -1] = 0
print(a)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
0 on the border
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
a = tile(array([[1, 0], [0, 1]]), (4, 4))    #10
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
                                 #11

In [ ]:
                                    #12

In [ ]:
                                              #13

In [48]:
a = zeros((5, 5))                               #14
a = a + arange(5)
print(a)          

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [35]:
array = linspace(0, 1, 12)                  #15
print(array[1:-1])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
